#!/bin/bash

#############################################
# Fail2ban + ipset 永久封禁自动配置脚本
# 用途：自动封禁 Sing-box 和 Snell 的端口扫描 IP
# 特性：使用 ipset 实现高性能永久封禁
# 版本：2.0
# 日期：2024-01-15
#############################################

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# 日志函数
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

log_success() {
    echo -e "${CYAN}[SUCCESS]${NC} $1"
}

# 检查是否为 root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "请使用 root 权限运行此脚本"
        echo "使用方法: sudo bash $0"
        exit 1
    fi
}

# 检测操作系统
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VER=$VERSION_ID
    else
        log_error "无法检测操作系统"
        exit 1
    fi
    
    log_info "检测到操作系统: $OS $VER"
}

# 安装 Fail2ban 和 ipset
install_packages() {
    log_step "安装 Fail2ban 和 ipset..."
    
    case $OS in
        ubuntu|debian)
            apt update
            apt install -y fail2ban python3-systemd iptables-persistent ipset ipset-persistent
            
            # 启用 netfilter-persistent
            systemctl enable netfilter-persistent 2>/dev/null || true
            ;;
        centos|rhel|fedora|rocky|alma)
            yum install -y epel-release
            yum install -y fail2ban fail2ban-systemd iptables-services ipset ipset-service
            
            systemctl enable iptables
            systemctl enable ipset
            ;;
        *)
            log_error "不支持的操作系统: $OS"
            exit 1
            ;;
    esac
    
    log_success "软件包安装完成"
}

# 检查服务是否存在
check_services() {
    log_step "检查代理服务..."
    
    SING_BOX_EXISTS=false
    SNELL_EXISTS=false
    
    if systemctl list-units --full --all | grep -q "sing-box.service"; then
        SING_BOX_EXISTS=true
        log_info "✓ 检测到 Sing-box 服务"
    else
        log_warn "✗ 未检测到 Sing-box 服务"
    fi
    
    if systemctl list-units --full --all | grep -q "snell-server.service"; then
        SNELL_EXISTS=true
        log_info "✓ 检测到 Snell 服务"
    else
        log_warn "✗ 未检测到 Snell 服务"
    fi
    
    if [ "$SING_BOX_EXISTS" = false ] && [ "$SNELL_EXISTS" = false ]; then
        log_error "未检测到任何代理服务，脚本退出"
        exit 1
    fi
}

# 创建 Sing-box 过滤器
create_singbox_filter() {
    log_step "创建 Sing-box 过滤器..."
    
    cat > /etc/fail2ban/filter.d/sing-box.conf << 'FILTER_EOF'
# Fail2ban filter for sing-box proxy
# Auto-generated by install script v2.0

[Definition]

# 匹配解密失败、验证失败等攻击特征
failregex = ^.*<WARN>.*Decryption failed.*from:\s*<HOST>
            ^.*Decryption failed.*from[:\s]+<HOST>
            ^.*verify failed.*from[:\s]+<HOST>
            ^.*hmac mismatch.*from[:\s]+<HOST>
            ^.*authentication failed.*<HOST>
            ^.*invalid.*from[:\s]+<HOST>
            ^.*error.*from[:\s]+<HOST>

# 忽略正常连接
ignoreregex = ^.*established.*<HOST>
              ^.*accepted.*<HOST>
              ^.*connected.*<HOST>

# journald 自动处理时间戳
datepattern = {^LN-BEG}

[Init]
maxlines = 1
journalmatch = _SYSTEMD_UNIT=sing-box.service
FILTER_EOF
    
    log_success "Sing-box 过滤器创建完成"
}

# 创建 Snell 过滤器
create_snell_filter() {
    log_step "创建 Snell 过滤器..."
    
    cat > /etc/fail2ban/filter.d/snell.conf << 'FILTER_EOF'
# Fail2ban filter for snell proxy
# Auto-generated by install script v2.0

[Definition]

# 匹配 Snell 特有的错误模式
failregex = ^.*<WARN>.*Decryption failed.*from:\s*<HOST>
            ^.*Decryption failed.*from[:\s]+<HOST>
            ^.*client hello verify failed.*<HOST>
            ^.*handshake failed.*<HOST>
            ^.*invalid.*from[:\s]+<HOST>
            ^.*error.*from[:\s]+<HOST>

ignoreregex = ^.*established.*<HOST>
              ^.*connected.*<HOST>
              ^.*accepted.*<HOST>

datepattern = {^LN-BEG}

[Init]
maxlines = 1
journalmatch = _SYSTEMD_UNIT=snell.service
FILTER_EOF
    
    log_success "Snell 过滤器创建完成"
}

# 创建 ipset 持久化动作
create_ipset_action() {
    log_step "创建 ipset 持久化动作..."
    
    cat > /etc/fail2ban/action.d/iptables-ipset-persistent.conf << 'ACTION_EOF'
# Fail2ban ipset action with persistence
# 带持久化的 ipset 动作 - 重启后保留封禁列表
# Auto-generated by install script v2.0

[INCLUDES]
before = iptables-common.conf

[Definition]

# 启动时创建 ipset 并从文件恢复
actionstart = ipset create <ipmset> hash:ip timeout 0 <familyopt> 2>/dev/null || ipset flush <ipmset>
              <iptables> -I <chain> -m set --match-set <ipmset> src -j <blocktype>
              # 从持久化文件恢复封禁列表
              if [ -f /var/lib/fail2ban/<ipmset>.restore ]; then
                  ipset restore < /var/lib/fail2ban/<ipmset>.restore 2>/dev/null || true
              fi

# 停止时保存 ipset 到文件
actionstop = mkdir -p /var/lib/fail2ban
             ipset save <ipmset> > /var/lib/fail2ban/<ipmset>.restore 2>/dev/null || true
             <iptables> -D <chain> -m set --match-set <ipmset> src -j <blocktype>
             ipset flush <ipmset>
             ipset destroy <ipmset>

# 刷新 ipset
actionflush = ipset flush <ipmset>

# 检查 ipset 是否存在
actioncheck = ipset list <ipmset> >/dev/null 2>&1

# 封禁 IP（添加到 ipset 并实时保存）
actionban = ipset add <ipmset> <ip> timeout 0 -exist
            mkdir -p /var/lib/fail2ban
            ipset save <ipmset> > /var/lib/fail2ban/<ipmset>.restore 2>/dev/null || true

# 解封 IP（从 ipset 删除并实时保存）
actionunban = ipset del <ipmset> <ip> -exist
              mkdir -p /var/lib/fail2ban
              ipset save <ipmset> > /var/lib/fail2ban/<ipmset>.restore 2>/dev/null || true

[Init]
# 默认参数
name = default
protocol = tcp
chain = INPUT
blocktype = DROP

# ipset 集合名称
ipmset = f2b-<name>

# IPv4 默认
familyopt =

[Init?family=inet6]
# IPv6 支持
familyopt = family inet6
ACTION_EOF
    
    log_success "ipset 持久化动作创建完成"
}

# 创建 Jail 配置
create_jail_config() {
    log_step "创建 Jail 配置..."
    
    # 获取用户输入
    echo ""
    echo "======================================"
    echo "  配置参数"
    echo "======================================"
    
    # 封禁时长选择
    echo ""
    echo "封禁时长选项："
    echo "  1) 永久封禁（推荐，使用 ipset）"
    echo "  2) 7天"
    echo "  3) 30天"
    echo "  4) 自定义"
    read -p "请选择 (1-4，默认1): " BAN_CHOICE
    BAN_CHOICE=${BAN_CHOICE:-1}
    
    case $BAN_CHOICE in
        1)
            BANTIME=-1
            log_info "已选择：永久封禁"
            ;;
        2)
            BANTIME=604800
            log_info "已选择：7天"
            ;;
        3)
            BANTIME=2592000
            log_info "已选择：30天"
            ;;
        4)
            read -p "请输入封禁时长（秒）: " BANTIME
            log_info "已选择：$BANTIME 秒"
            ;;
        *)
            BANTIME=-1
            log_warn "无效选择，使用默认：永久封禁"
            ;;
    esac
    
    read -p "时间窗口（秒，默认300=5分钟）: " FINDTIME
    FINDTIME=${FINDTIME:-300}
    
    read -p "失败次数阈值（默认3次）: " MAXRETRY
    MAXRETRY=${MAXRETRY:-3}
    
    read -p "是否添加白名单 IP？(y/n，默认n): " ADD_WHITELIST
    ADD_WHITELIST=${ADD_WHITELIST:-n}
    
    WHITELIST_IPS=""
    if [ "$ADD_WHITELIST" = "y" ] || [ "$ADD_WHITELIST" = "Y" ]; then
        echo "提示：请输入你的可信 IP 地址，多个用空格分隔"
        echo "示例：192.168.1.100 10.0.0.5"
        read -p "白名单 IP: " WHITELIST_IPS
    fi
    
    # 生成配置文件
    cat > /etc/fail2ban/jail.d/proxy.conf << JAIL_EOF
# Fail2ban jail configuration for proxy services
# 使用 ipset 实现高性能永久封禁
# Auto-generated by install script v2.0
# Generated at: $(date)

[DEFAULT]
# ============ 全局默认设置 ============

# 封禁时长（-1 = 永久）
bantime  = $BANTIME

# 时间窗口（秒）
findtime = $FINDTIME

# 失败次数阈值
maxretry = $MAXRETRY

# 白名单 IP
ignoreip = 127.0.0.1/8 
           ::1
           $WHITELIST_IPS

# 使用 ipset 动作（高性能）
banaction = iptables-ipset-persistent
banaction_allports = iptables-ipset-persistent

JAIL_EOF

    # 添加 Sing-box jail
    if [ "$SING_BOX_EXISTS" = true ]; then
        cat >> /etc/fail2ban/jail.d/proxy.conf << 'JAIL_EOF'

# ============ Sing-box Jail ============
[sing-box]
enabled   = true
backend   = systemd
filter    = sing-box

# 使用 ipset 持久化动作
action    = iptables-ipset-persistent[name=sing-box, protocol=all]

journalmatch = _SYSTEMD_UNIT=sing-box.service

# 日志级别
loglevel  = INFO
JAIL_EOF
        log_info "✓ 已添加 Sing-box jail"
    fi
    
    # 添加 Snell jail
    if [ "$SNELL_EXISTS" = true ]; then
        cat >> /etc/fail2ban/jail.d/proxy.conf << 'JAIL_EOF'

# ============ Snell Jail ============
[snell]
enabled   = true
backend   = systemd
filter    = snell

# 使用 ipset 持久化动作
action    = iptables-ipset-persistent[name=snell, protocol=all]

journalmatch = _SYSTEMD_UNIT=snell.service

# 日志级别
loglevel  = INFO
JAIL_EOF
        log_info "✓ 已添加 Snell jail"
    fi
    
    # 添加 SSH 保护（可选）
    read -p "是否启用 SSH 保护？(y/n，默认y): " ENABLE_SSH
    ENABLE_SSH=${ENABLE_SSH:-y}
    
    if [ "$ENABLE_SSH" = "y" ] || [ "$ENABLE_SSH" = "Y" ]; then
        cat >> /etc/fail2ban/jail.d/proxy.conf << 'JAIL_EOF'

# ============ SSH 保护 ============
[sshd]
enabled   = true
maxretry  = 5
findtime  = 600
bantime   = 3600
action    = iptables-ipset-persistent[name=sshd, protocol=tcp, port=ssh]
JAIL_EOF
        log_info "✓ 已启用 SSH 保护"
    fi
    
    log_success "Jail 配置创建完成"
}

# 测试过滤器
test_filters() {
    log_step "测试过滤器配置..."
    
    if [ "$SING_BOX_EXISTS" = true ]; then
        echo ""
        log_info "测试 Sing-box 过滤器..."
        if journalctl -u sing-box --since "1 day ago" 2>/dev/null | \
            fail2ban-regex - /etc/fail2ban/filter.d/sing-box.conf 2>/dev/null | \
            grep -q "matched"; then
            log_success "Sing-box 过滤器测试通过"
        else
            log_warn "Sing-box 暂无匹配日志（正常，等待实际攻击）"
        fi
    fi
    
    if [ "$SNELL_EXISTS" = true ]; then
        echo ""
        log_info "测试 Snell 过滤器..."
        if journalctl -u snell --since "1 day ago" 2>/dev/null | \
            fail2ban-regex - /etc/fail2ban/filter.d/snell.conf 2>/dev/null | \
            grep -q "matched"; then
            log_success "Snell 过滤器测试通过"
        else
            log_warn "Snell 暂无匹配日志（正常，等待实际攻击）"
        fi
    fi
}

# 验证配置
verify_config() {
    log_step "验证配置语法..."
    
    if fail2ban-client -t > /dev/null 2>&1; then
        log_success "配置语法正确"
    else
        log_error "配置语法错误"
        fail2ban-client -t
        exit 1
    fi
}

# 启动服务
start_service() {
    log_step "启动 Fail2ban 服务..."
    
    systemctl enable fail2ban
    systemctl restart fail2ban
    
    sleep 3
    
    if systemctl is-active --quiet fail2ban; then
        log_success "Fail2ban 服务启动成功"
    else
        log_error "Fail2ban 服务启动失败"
        systemctl status fail2ban
        exit 1
    fi
}

# 验证 ipset
verify_ipset() {
    log_step "验证 ipset 配置..."
    
    sleep 2
    
    if [ "$SING_BOX_EXISTS" = true ]; then
        if ipset list f2b-sing-box >/dev/null 2>&1; then
            log_success "✓ Sing-box ipset 创建成功"
        else
            log_warn "✗ Sing-box ipset 未创建（可能需要等待）"
        fi
    fi
    
    if [ "$SNELL_EXISTS" = true ]; then
        if ipset list f2b-snell >/dev/null 2>&1; then
            log_success "✓ Snell ipset 创建成功"
        else
            log_warn "✗ Snell ipset 未创建（可能需要等待）"
        fi
    fi
}

# 显示状态
show_status() {
    log_step "显示当前状态..."
    
    echo ""
    echo "======================================"
    echo "  Fail2ban 状态"
    echo "======================================"
    
    fail2ban-client status
    
    echo ""
    if [ "$SING_BOX_EXISTS" = true ]; then
        echo "【Sing-box Jail】"
        fail2ban-client status sing-box 2>/dev/null || echo "等待初始化..."
        echo ""
    fi
    
    if [ "$SNELL_EXISTS" = true ]; then
        echo "【Snell Jail】"
        fail2ban-client status snell 2>/dev/null || echo "等待初始化..."
        echo ""
    fi
    
    echo "【ipset 列表】"
    ipset list -n 2>/dev/null | grep "^f2b-" || echo "等待创建..."
    echo ""
    
    echo "【iptables 规则】"
    iptables -L INPUT -n -v | grep "f2b-" || echo "等待创建..."
    echo ""
}

# 创建监控脚本
create_monitor_script() {
    log_step "创建监控脚本..."
    
    cat > /usr/local/bin/fail2ban-monitor << 'MONITOR_EOF'
#!/bin/bash
# Fail2ban + ipset 实时监控脚本

show_status() {
    clear
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║         Fail2ban + ipset 实时监控                          ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    echo "更新时间: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "按 Ctrl+C 退出"
    echo ""
    
    # 显示封禁配置
    echo "┌─ 封禁配置 ─────────────────────────────────────────────┐"
    for jail in $(fail2ban-client status 2>/dev/null | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
        bantime=$(fail2ban-client get $jail bantime 2>/dev/null)
        if [ "$bantime" = "-1" ]; then
            printf "│ %-15s : 永久封禁 ✓\n" "$jail"
        else
            printf "│ %-15s : %d 秒\n" "$jail" "$bantime"
        fi
    done
    echo "└────────────────────────────────────────────────────────┘"
    echo ""
    
    # 显示封禁统计
    echo "┌─ 封禁统计 ─────────────────────────────────────────────┐"
    for jail in $(fail2ban-client status 2>/dev/null | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
        total=$(fail2ban-client status $jail 2>/dev/null | grep "Total banned" | awk '{print $NF}')
        current=$(fail2ban-client status $jail 2>/dev/null | grep "Currently banned" | awk '{print $NF}')
        printf "│ %-15s : 总计 %-5s 次，当前 %-5s 个\n" "$jail" "$total" "$current"
    done
    echo "└────────────────────────────────────────────────────────┘"
    echo ""
    
    # 显示 ipset 统计
    if command -v ipset >/dev/null 2>&1; then
        echo "┌─ ipset 统计 ───────────────────────────────────────────┐"
        for set in $(ipset list -n 2>/dev/null | grep "^f2b-"); do
            count=$(ipset list $set 2>/dev/null | grep -c "^[0-9]" || echo "0")
            size=$(ipset list $set 2>/dev/null | grep "Size in memory" | awk '{print $4}')
            printf "│ %-20s : %-5s 个 IP (内存: %s)\n" "$set" "$count" "$size"
        done
        echo "└────────────────────────────────────────────────────────┘"
        echo ""
    fi
    
    # 最近封禁
    echo "┌─ 最近封禁 (最后 5 条) ─────────────────────────────────┐"
    tail -n 5 /var/log/fail2ban.log 2>/dev/null | grep "Ban " | while read line; do
        echo "│ $line"
    done || echo "│ 暂无封禁记录"
    echo "└────────────────────────────────────────────────────────┘"
    echo ""
    
    # 持久化文件
    echo "┌─ 持久化数据 ───────────────────────────────────────────┐"
    if [ -d /var/lib/fail2ban ]; then
        for f in /var/lib/fail2ban/*.restore; do
            if [ -f "$f" ]; then
                lines=$(grep -c "add f2b-" "$f" 2>/dev/null || echo "0")
                printf "│ %-30s : %s 条记录\n" "$(basename $f)" "$lines"
            fi
        done
    else
        echo "│ 暂无持久化数据"
    fi
    echo "└────────────────────────────────────────────────────────┘"
}

while true; do
    show_status
    sleep 5
done
MONITOR_EOF
    
    chmod +x /usr/local/bin/fail2ban-monitor
    log_success "已创建监控脚本: fail2ban-monitor"
}

# 创建统计脚本
create_stats_script() {
    log_step "创建统计脚本..."
    
    cat > /usr/local/bin/fail2ban-stats << 'STATS_EOF'
#!/bin/bash
# Fail2ban 统计脚本

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Fail2ban 统计信息                                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# 封禁次数最多的 IP
echo "┌─ 封禁次数最多的 IP (Top 10) ──────────────────────────────┐"
grep "Ban " /var/log/fail2ban.log 2>/dev/null | \
    grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | \
    sort | uniq -c | sort -rn | head -10 | \
    awk '{printf "│ %3d 次  %s\n", $1, $2}'
echo "└────────────────────────────────────────────────────────┘"
echo ""

# 各 Jail 统计
echo "┌─ 各 Jail 封禁统计 ─────────────────────────────────────────┐"
for jail in $(fail2ban-client status 2>/dev/null | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
    total=$(fail2ban-client status $jail 2>/dev/null | grep "Total banned" | awk '{print $NF}')
    current=$(fail2ban-client status $jail 2>/dev/null | grep "Currently banned" | awk '{print $NF}')
    printf "│ %-15s : 总计 %-6s 次，当前 %-6s 个\n" "$jail" "$total" "$current"
done
echo "└────────────────────────────────────────────────────────┘"
echo ""

# 今日统计
echo "┌─ 今日统计 ─────────────────────────────────────────────────┐"
today=$(date '+%Y-%m-%d')
ban_count=$(grep "Ban " /var/log/fail2ban.log 2>/dev/null | grep "$today" | wc -l)
unban_count=$(grep "Unban " /var/log/fail2ban.log 2>/dev/null | grep "$today" | wc -l)
printf "│ 今日封禁: %-10s 次\n" "$ban_count"
printf "│ 今日解封: %-10s 次\n" "$unban_count"
echo "└────────────────────────────────────────────────────────┘"
echo ""

# 当前被封禁的 IP
echo "┌─ 当前所有被封禁的 IP ──────────────────────────────────────┐"
for jail in $(fail2ban-client status 2>/dev/null | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
    echo "│"
    echo "│ [$jail]"
    banned=$(fail2ban-client get $jail banip 2>/dev/null)
    if [ -n "$banned" ]; then
        echo "$banned" | while read ip; do
            echo "│   - $ip"
        done
    else
        echo "│   (无)"
    fi
done
echo "└────────────────────────────────────────────────────────┘"
echo ""

# ipset 详细信息
if command -v ipset >/dev/null 2>&1; then
    echo "┌─ ipset 详细信息 ───────────────────────────────────────────┐"
    for set in $(ipset list -n 2>/dev/null | grep "^f2b-"); do
        echo "│"
        echo "│ [$set]"
        count=$(ipset list $set 2>/dev/null | grep -c "^[0-9]" || echo "0")
        size=$(ipset list $set 2>/dev/null | grep "Size in memory" | awk '{print $4}')
        maxelem=$(ipset list $set 2>/dev/null | grep "maxelem" | grep -oE '[0-9]+' | tail -1)
        printf "│   IP 数量: %s\n" "$count"
        printf "│   内存占用: %s\n" "$size"
        printf "│   最大容量: %s\n" "$maxelem"
    done
    echo "└────────────────────────────────────────────────────────┘"
fi
STATS_EOF
    
    chmod +x /usr/local/bin/fail2ban-stats
    log_success "已创建统计脚本: fail2ban-stats"
}

# 创建解封脚本
create_unban_script() {
    log_step "创建解封脚本..."
    
    cat > /usr/local/bin/fail2ban-unban << 'UNBAN_EOF'
#!/bin/bash
# Fail2ban 解封脚本

if [ -z "$1" ]; then
    echo "用法: $0 <IP地址|all>"
    echo ""
    echo "示例："
    echo "  $0 1.2.3.4        # 解封单个 IP"
    echo "  $0 all            # 解封所有 IP"
    echo ""
    exit 1
fi

if [ "$1" = "all" ]; then
    echo "解封所有 IP..."
    fail2ban-client unban --all
    echo "✓ 完成"
else
    echo "解封 IP: $1"
    for jail in $(fail2ban-client status 2>/dev/null | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
        if fail2ban-client set $jail unbanip $1 2>/dev/null; then
            echo "✓ 已从 $jail 解封"
        fi
    done
    echo "✓ 完成"
fi
UNBAN_EOF
    
    chmod +x /usr/local/bin/fail2ban-unban
    log_success "已创建解封脚本: fail2ban-unban"
}

# 创建备份脚本
create_backup_script() {
    log_step "创建备份脚本..."
    
    cat > /usr/local/bin/fail2ban-backup << 'BACKUP_EOF'
#!/bin/bash
# Fail2ban 备份脚本

BACKUP_DIR="/var/backups/fail2ban"
DATE=$(date +%Y%m%d_%H%M%S)

echo "开始备份 Fail2ban 配置和数据..."

# 创建备份目录
mkdir -p "$BACKUP_DIR"

# 备份配置文件
echo "备份配置文件..."
tar -czf "$BACKUP_DIR/fail2ban-config-$DATE.tar.gz" \
    /etc/fail2ban/jail.d/ \
    /etc/fail2ban/filter.d/sing-box.conf \
    /etc/fail2ban/filter.d/snell.conf \
    /etc/fail2ban/action.d/iptables-ipset-persistent.conf \
    2>/dev/null

# 备份封禁列表
echo "备份封禁列表..."
for jail in $(fail2ban-client status 2>/dev/null | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
    fail2ban-client get $jail banip > "$BACKUP_DIR/${jail}-banlist-$DATE.txt" 2>/dev/null
done

# 备份 ipset
echo "备份 ipset..."
for set in $(ipset list -n 2>/dev/null | grep "^f2b-"); do
    ipset save $set > "$BACKUP_DIR/${set}-$DATE.ipset" 2>/dev/null
done

# 备份持久化文件
if [ -d /var/lib/fail2ban ]; then
    echo "备份持久化文件..."
    cp -r /var/lib/fail2ban "$BACKUP_DIR/persistent-$DATE"
fi

echo "✓ 备份完成"
echo "备份位置: $BACKUP_DIR"
ls -lh "$BACKUP_DIR" | tail -5
BACKUP_EOF
    
    chmod +x /usr/local/bin/fail2ban-backup
    log_success "已创建备份脚本: fail2ban-backup"
}

# 创建卸载脚本
create_uninstall_script() {
    log_step "创建卸载脚本..."
    
    cat > /usr/local/bin/uninstall-fail2ban << 'UNINSTALL_EOF'
#!/bin/bash
# Fail2ban 完全卸载脚本

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Fail2ban 卸载程序                                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "警告: 此操作将完全卸载 Fail2ban、ipset 及其所有配置"
echo ""
read -p "确认继续？输入 'yes' 确认: " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "已取消"
    exit 0
fi

echo ""
echo "[1/6] 停止服务..."
systemctl stop fail2ban
systemctl disable fail2ban

echo "[2/6] 清理 iptables 规则..."
for chain in $(iptables -L -n | grep "^Chain f2b-" | awk '{print $2}'); do
    iptables -F $chain 2>/dev/null
    iptables -X $chain 2>/dev/null
done

echo "[3/6] 清理 ipset..."
for set in $(ipset list -n 2>/dev/null | grep "^f2b-"); do
    ipset destroy $set 2>/dev/null
done

echo "[4/6] 删除配置文件..."
rm -rf /etc/fail2ban/jail.d/proxy.conf
rm -rf /etc/fail2ban/filter.d/sing-box.conf
rm -rf /etc/fail2ban/filter.d/snell.conf
rm -rf /etc/fail2ban/action.d/iptables-ipset-persistent.conf
rm -rf /var/lib/fail2ban/*.restore

echo "[5/6] 卸载软件包..."
if command -v apt > /dev/null; then
    apt remove --purge -y fail2ban ipset
elif command -v yum > /dev/null; then
    yum remove -y fail2ban ipset
fi

echo "[6/6] 删除管理脚本..."
rm -f /usr/local/bin/fail2ban-monitor
rm -f /usr/local/bin/fail2ban-stats
rm -f /usr/local/bin/fail2ban-unban
rm -f /usr/local/bin/fail2ban-backup
rm -f /usr/local/bin/uninstall-fail2ban

echo ""
echo "✓ 卸载完成"
UNINSTALL_EOF
    
    chmod +x /usr/local/bin/uninstall-fail2ban
    log_success "已创建卸载脚本: uninstall-fail2ban"
}

# 显示使用说明
show_usage() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║         安装完成！                                         ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    echo "┌─ 常用命令 ─────────────────────────────────────────────────┐"
    echo "│ 实时监控:        fail2ban-monitor                          │"
    echo "│ 查看统计:        fail2ban-stats                            │"
    echo "│ 解封 IP:         fail2ban-unban <IP>                       │"
    echo "│ 解封所有:        fail2ban-unban all                        │"
    echo "│ 备份数据:        fail2ban-backup                           │"
    echo "│ 查看状态:        fail2ban-client status                    │"
    echo "│ 查看日志:        tail -f /var/log/fail2ban.log             │"
    echo "└────────────────────────────────────────────────────────────┘"
    echo ""
    echo "┌─ ipset 命令 ───────────────────────────────────────────────┐"
    echo "│ 查看所有 ipset:  ipset list                                │"
    echo "│ 查看指定 ipset:  ipset list f2b-sing-box                   │"
    echo "│ 统计 IP 数量:    ipset list f2b-sing-box | grep -c '^[0-9]'│"
    echo "└────────────────────────────────────────────────────────────┘"
    echo ""
    echo "┌─ 配置文件位置 ─────────────────────────────────────────────┐"
    echo "│ 主配置:          /etc/fail2ban/jail.d/proxy.conf           │"
    echo "│ Sing-box 过滤器: /etc/fail2ban/filter.d/sing-box.conf      │"
    echo "│ Snell 过滤器:    /etc/fail2ban/filter.d/snell.conf         │"
    echo "│ ipset 动作:      /etc/fail2ban/action.d/iptables-ipset-... │"
    echo "│ 持久化数据:      /var/lib/fail2ban/*.restore               │"
    echo "└────────────────────────────────────────────────────────────┘"
    echo ""
    echo "┌─ 当前配置 ─────────────────────────────────────────────────┐"
    if [ "$BANTIME" = "-1" ]; then
        echo "│ 封禁时长:        永久封禁 ✓                                │"
    else
        printf "│ 封禁时长:        %-6s 秒 (%.1f 小时)\n" "$BANTIME" "$(echo "scale=1; $BANTIME/3600" | bc)"
    fi
    printf "│ 时间窗口:        %-6s 秒 (%d 分钟)                    │\n" "$FINDTIME" "$(($FINDTIME/60))"
    printf "│ 失败阈值:        %-6s 次                                  │\n" "$MAXRETRY"
    echo "│ 封禁方式:        ipset (高性能) ✓                          │"
    echo "│ 持久化:          已启用 (重启后保留) ✓                     │"
    echo "└────────────────────────────────────────────────────────────┘"
    echo ""
    echo "┌─ 测试封禁 ─────────────────────────────────────────────────┐"
    echo "│ # 手动封禁测试 IP                                          │"
    echo "│ fail2ban-client set sing-box banip 1.2.3.4                 │"
    echo "│                                                            │"
    echo "│ # 查看 ipset                                               │"
    echo "│ ipset list f2b-sing-box                                    │"
    echo "│                                                            │"
    echo "│ # 解封测试 IP                                              │"
    echo "│ fail2ban-unban 1.2.3.4                                     │"
    echo "└────────────────────────────────────────────────────────────┘"
    echo ""
    echo "┌─ 卸载 ─────────────────────────────────────────────────────┐"
    echo "│ 运行命令:        uninstall-fail2ban                        │"
    echo "└────────────────────────────────────────────────────────────┘"
    echo ""
}

# 主函数
main() {
    clear
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║   Fail2ban + ipset 永久封禁自动安装脚本                    ║"
    echo "║   版本: 2.0                                                ║"
    echo "║   特性: 高性能 | 永久封禁 | 重启保留                       ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    
    check_root
    detect_os
    
    # 检查是否已安装
    if command -v fail2ban-client > /dev/null 2>&1; then
        log_warn "检测到 Fail2ban 已安装"
        read -p "是否重新配置？(y/n): " RECONFIG
        if [ "$RECONFIG" != "y" ] && [ "$RECONFIG" != "Y" ]; then
            log_info "退出安装"
            exit 0
        fi
        
        # 备份现有配置
        if [ -f /etc/fail2ban/jail.d/proxy.conf ]; then
            log_info "备份现有配置..."
            cp /etc/fail2ban/jail.d/proxy.conf \
               /etc/fail2ban/jail.d/proxy.conf.bak.$(date +%Y%m%d_%H%M%S)
        fi
    else
        install_packages
    fi
    
    check_services
    
    if [ "$SING_BOX_EXISTS" = true ]; then
        create_singbox_filter
    fi
    
    if [ "$SNELL_EXISTS" = true ]; then
        create_snell_filter
    fi
    
    create_ipset_action
    create_jail_config
    test_filters
    verify_config
    start_service
    verify_ipset
    show_status
    create_monitor_script
    create_stats_script
    create_unban_script
    create_backup_script
    create_uninstall_script
    show_usage
    
    log_success "安装完成！建议运行 'fail2ban-monitor' 查看实时状态"
}

# 执行主函数
main
