#!/bin/bash

#############################################
# Fail2ban 自动配置脚本
# 用途：自动封禁 Sing-box 和 Snell 的端口扫描 IP
# 作者：Assistant
# 日期：2024-01-15
#############################################

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 日志函数
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# 检查是否为 root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "请使用 root 权限运行此脚本"
        echo "使用方法: sudo bash $0"
        exit 1
    fi
}

# 检测操作系统
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VER=$VERSION_ID
    else
        log_error "无法检测操作系统"
        exit 1
    fi
    
    log_info "检测到操作系统: $OS $VER"
}

# 安装 Fail2ban
install_fail2ban() {
    log_step "安装 Fail2ban..."
    
    case $OS in
        ubuntu|debian)
            apt update
            apt install -y fail2ban python3-systemd iptables-persistent
            ;;
        centos|rhel|fedora)
            yum install -y epel-release
            yum install -y fail2ban fail2ban-systemd iptables-services
            systemctl enable iptables
            ;;
        *)
            log_error "不支持的操作系统: $OS"
            exit 1
            ;;
    esac
    
    log_info "Fail2ban 安装完成"
}

# 检查服务是否存在
check_services() {
    log_step "检查代理服务..."
    
    SING_BOX_EXISTS=false
    SNELL_EXISTS=false
    
    if systemctl list-units --full --all | grep -q "sing-box.service"; then
        SING_BOX_EXISTS=true
        log_info "检测到 Sing-box 服务"
    else
        log_warn "未检测到 Sing-box 服务"
    fi
    
    if systemctl list-units --full --all | grep -q "snell-server.service"; then
        SNELL_EXISTS=true
        log_info "检测到 Snell 服务"
    else
        log_warn "未检测到 Snell 服务"
    fi
    
    if [ "$SING_BOX_EXISTS" = false ] && [ "$SNELL_EXISTS" = false ]; then
        log_error "未检测到任何代理服务，脚本退出"
        exit 1
    fi
}

# 创建 Sing-box 过滤器
create_singbox_filter() {
    log_step "创建 Sing-box 过滤器..."
    
    cat > /etc/fail2ban/filter.d/sing-box.conf << 'FILTER_EOF'
# Fail2ban filter for sing-box proxy
# Auto-generated by install script

[Definition]

# 匹配解密失败、验证失败等攻击特征
failregex = ^.*<WARN>.*Decryption failed.*from:\s*<HOST>
            ^.*Decryption failed.*from[:\s]+<HOST>
            ^.*verify failed.*from[:\s]+<HOST>
            ^.*hmac mismatch.*from[:\s]+<HOST>
            ^.*authentication failed.*<HOST>
            ^.*invalid.*from[:\s]+<HOST>
            ^.*error.*from[:\s]+<HOST>

# 忽略正常连接
ignoreregex = ^.*established.*<HOST>
              ^.*accepted.*<HOST>
              ^.*connected.*<HOST>

# journald 自动处理时间戳
datepattern = {^LN-BEG}

[Init]
maxlines = 1
journalmatch = _SYSTEMD_UNIT=sing-box.service
FILTER_EOF
    
    log_info "Sing-box 过滤器创建完成"
}

# 创建 Snell 过滤器
create_snell_filter() {
    log_step "创建 Snell 过滤器..."
    
    cat > /etc/fail2ban/filter.d/snell.conf << 'FILTER_EOF'
# Fail2ban filter for snell proxy
# Auto-generated by install script

[Definition]

# 匹配 Snell 特有的错误模式
failregex = ^.*<WARN>.*Decryption failed.*from:\s*<HOST>
            ^.*Decryption failed.*from[:\s]+<HOST>
            ^.*client hello verify failed.*<HOST>
            ^.*handshake failed.*<HOST>
            ^.*invalid.*from[:\s]+<HOST>
            ^.*error.*from[:\s]+<HOST>

ignoreregex = ^.*established.*<HOST>
              ^.*connected.*<HOST>
              ^.*accepted.*<HOST>

datepattern = {^LN-BEG}

[Init]
maxlines = 1
journalmatch = _SYSTEMD_UNIT=snell.service
FILTER_EOF
    
    log_info "Snell 过滤器创建完成"
}

# 创建 Jail 配置
create_jail_config() {
    log_step "创建 Jail 配置..."
    
    # 获取用户输入
    echo ""
    echo "======================================"
    echo "  配置参数"
    echo "======================================"
    
    read -p "封禁时长（秒，默认86400=24小时）: " BANTIME
    BANTIME=${BANTIME:-86400}
    
    read -p "时间窗口（秒，默认300=5分钟）: " FINDTIME
    FINDTIME=${FINDTIME:-300}
    
    read -p "失败次数阈值（默认3次）: " MAXRETRY
    MAXRETRY=${MAXRETRY:-3}
    
    read -p "是否添加白名单 IP？(y/n，默认n): " ADD_WHITELIST
    ADD_WHITELIST=${ADD_WHITELIST:-n}
    
    WHITELIST_IPS=""
    if [ "$ADD_WHITELIST" = "y" ] || [ "$ADD_WHITELIST" = "Y" ]; then
        read -p "请输入白名单 IP（多个用空格分隔）: " WHITELIST_IPS
    fi
    
    # 生成配置文件
    cat > /etc/fail2ban/jail.d/proxy.conf << JAIL_EOF
# Fail2ban jail configuration for proxy services
# Auto-generated by install script
# Generated at: $(date)

[DEFAULT]
# ============ 全局默认设置 ============
bantime  = $BANTIME
findtime = $FINDTIME
maxretry = $MAXRETRY

# 白名单
ignoreip = 127.0.0.1/8 
           ::1
           $WHITELIST_IPS

banaction = iptables-allports
banaction_allports = iptables-allports

JAIL_EOF

    # 添加 Sing-box jail
    if [ "$SING_BOX_EXISTS" = true ]; then
        cat >> /etc/fail2ban/jail.d/proxy.conf << 'JAIL_EOF'

# ============ Sing-box Jail ============
[sing-box]
enabled   = true
backend   = systemd
filter    = sing-box
action    = iptables-allports[name=sing-box, protocol=all]
journalmatch = _SYSTEMD_UNIT=sing-box.service
JAIL_EOF
        log_info "已添加 Sing-box jail"
    fi
    
    # 添加 Snell jail
    if [ "$SNELL_EXISTS" = true ]; then
        cat >> /etc/fail2ban/jail.d/proxy.conf << 'JAIL_EOF'

# ============ Snell Jail ============
[snell]
enabled   = true
backend   = systemd
filter    = snell
action    = iptables-allports[name=snell, protocol=all]
journalmatch = _SYSTEMD_UNIT=snell.service
JAIL_EOF
        log_info "已添加 Snell jail"
    fi
    
    # 添加 SSH 保护（可选）
    read -p "是否启用 SSH 保护？(y/n，默认y): " ENABLE_SSH
    ENABLE_SSH=${ENABLE_SSH:-y}
    
    if [ "$ENABLE_SSH" = "y" ] || [ "$ENABLE_SSH" = "Y" ]; then
        cat >> /etc/fail2ban/jail.d/proxy.conf << 'JAIL_EOF'

# ============ SSH 保护 ============
[sshd]
enabled   = true
maxretry  = 5
findtime  = 600
bantime   = 3600
JAIL_EOF
        log_info "已启用 SSH 保护"
    fi
    
    log_info "Jail 配置创建完成"
}

# 测试过滤器
test_filters() {
    log_step "测试过滤器配置..."
    
    if [ "$SING_BOX_EXISTS" = true ]; then
        echo ""
        log_info "测试 Sing-box 过滤器..."
        journalctl -u sing-box --since "1 day ago" 2>/dev/null | \
            fail2ban-regex - /etc/fail2ban/filter.d/sing-box.conf | \
            grep -E "matched|missed" || log_warn "无测试数据"
    fi
    
    if [ "$SNELL_EXISTS" = true ]; then
        echo ""
        log_info "测试 Snell 过滤器..."
        journalctl -u snell --since "1 day ago" 2>/dev/null | \
            fail2ban-regex - /etc/fail2ban/filter.d/snell.conf | \
            grep -E "matched|missed" || log_warn "无测试数据"
    fi
}

# 验证配置
verify_config() {
    log_step "验证配置语法..."
    
    if fail2ban-client -t > /dev/null 2>&1; then
        log_info "配置语法正确"
    else
        log_error "配置语法错误"
        fail2ban-client -t
        exit 1
    fi
}

# 启动服务
start_service() {
    log_step "启动 Fail2ban 服务..."
    
    systemctl enable fail2ban
    systemctl restart fail2ban
    
    sleep 2
    
    if systemctl is-active --quiet fail2ban; then
        log_info "Fail2ban 服务启动成功"
    else
        log_error "Fail2ban 服务启动失败"
        systemctl status fail2ban
        exit 1
    fi
}

# 显示状态
show_status() {
    log_step "显示当前状态..."
    
    echo ""
    echo "======================================"
    echo "  Fail2ban 状态"
    echo "======================================"
    
    fail2ban-client status
    
    echo ""
    if [ "$SING_BOX_EXISTS" = true ]; then
        echo "【Sing-box Jail】"
        fail2ban-client status sing-box
        echo ""
    fi
    
    if [ "$SNELL_EXISTS" = true ]; then
        echo "【Snell Jail】"
        fail2ban-client status snell
        echo ""
    fi
}

# 创建管理脚本
create_management_scripts() {
    log_step "创建管理脚本..."
    
    # 监控脚本
    cat > /usr/local/bin/fail2ban-monitor << 'MONITOR_EOF'
#!/bin/bash
# Fail2ban 实时监控脚本

show_status() {
    clear
    echo "=== Fail2ban 实时监控 ==="
    echo "更新时间: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "按 Ctrl+C 退出"
    echo ""
    
    fail2ban-client status 2>/dev/null
    echo ""
    
    echo "【最近封禁记录】"
    tail -n 10 /var/log/fail2ban.log | grep "Ban " || echo "暂无"
    echo ""
    
    echo "【iptables 规则统计】"
    for chain in $(iptables -L -n | grep "^Chain f2b-" | awk '{print $2}'); do
        count=$(iptables -L $chain -n | grep -c DROP)
        echo "$chain: $count 个封禁"
    done
}

while true; do
    show_status
    sleep 5
done
MONITOR_EOF
    
    chmod +x /usr/local/bin/fail2ban-monitor
    log_info "已创建监控脚本: /usr/local/bin/fail2ban-monitor"
    
    # 统计脚本
    cat > /usr/local/bin/fail2ban-stats << 'STATS_EOF'
#!/bin/bash
# Fail2ban 统计脚本

echo "=== Fail2ban 统计信息 ==="
echo ""

echo "【封禁次数最多的 IP (Top 10)】"
grep "Ban " /var/log/fail2ban.log | \
    grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | \
    sort | uniq -c | sort -rn | head -10
echo ""

echo "【各 Jail 封禁统计】"
for jail in $(fail2ban-client status | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
    total=$(fail2ban-client status $jail | grep "Total banned" | awk '{print $NF}')
    current=$(fail2ban-client status $jail | grep "Currently banned" | awk '{print $NF}')
    echo "$jail: 总计 $total 次，当前 $current 个"
done
echo ""

echo "【今日封禁记录】"
grep "Ban " /var/log/fail2ban.log | grep "$(date '+%Y-%m-%d')" | wc -l
echo ""

echo "【当前所有被封禁的 IP】"
for jail in $(fail2ban-client status | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
    banned=$(fail2ban-client get $jail banip 2>/dev/null)
    if [ -n "$banned" ]; then
        echo "[$jail]"
        echo "$banned"
        echo ""
    fi
done
STATS_EOF
    
    chmod +x /usr/local/bin/fail2ban-stats
    log_info "已创建统计脚本: /usr/local/bin/fail2ban-stats"
    
    # 解封脚本
    cat > /usr/local/bin/fail2ban-unban << 'UNBAN_EOF'
#!/bin/bash
# Fail2ban 解封脚本

if [ -z "$1" ]; then
    echo "用法: $0 <IP地址|all>"
    echo "示例: $0 1.2.3.4"
    echo "      $0 all  (解封所有IP)"
    exit 1
fi

if [ "$1" = "all" ]; then
    echo "解封所有 IP..."
    fail2ban-client unban --all
    echo "完成"
else
    echo "解封 IP: $1"
    for jail in $(fail2ban-client status | grep "Jail list" | cut -d: -f2 | tr ',' ' '); do
        fail2ban-client set $jail unbanip $1 2>/dev/null && echo "已从 $jail 解封"
    done
    echo "完成"
fi
UNBAN_EOF
    
    chmod +x /usr/local/bin/fail2ban-unban
    log_info "已创建解封脚本: /usr/local/bin/fail2ban-unban"
}

# 创建卸载脚本
create_uninstall_script() {
    log_step "创建卸载脚本..."
    
    cat > /usr/local/bin/uninstall-fail2ban << 'UNINSTALL_EOF'
#!/bin/bash
# Fail2ban 卸载脚本

echo "警告: 此操作将完全卸载 Fail2ban 及其配置"
read -p "确认继续？(yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "已取消"
    exit 0
fi

echo "停止服务..."
systemctl stop fail2ban
systemctl disable fail2ban

echo "清理 iptables 规则..."
for chain in $(iptables -L -n | grep "^Chain f2b-" | awk '{print $2}'); do
    iptables -F $chain
    iptables -X $chain
done

echo "删除配置文件..."
rm -rf /etc/fail2ban/jail.d/proxy.conf
rm -rf /etc/fail2ban/filter.d/sing-box.conf
rm -rf /etc/fail2ban/filter.d/snell.conf

echo "卸载软件包..."
if command -v apt > /dev/null; then
    apt remove --purge -y fail2ban
elif command -v yum > /dev/null; then
    yum remove -y fail2ban
fi

echo "删除管理脚本..."
rm -f /usr/local/bin/fail2ban-monitor
rm -f /usr/local/bin/fail2ban-stats
rm -f /usr/local/bin/fail2ban-unban
rm -f /usr/local/bin/uninstall-fail2ban

echo "卸载完成"
UNINSTALL_EOF
    
    chmod +x /usr/local/bin/uninstall-fail2ban
    log_info "已创建卸载脚本: /usr/local/bin/uninstall-fail2ban"
}

# 显示使用说明
show_usage() {
    echo ""
    echo "======================================"
    echo "  安装完成！"
    echo "======================================"
    echo ""
    echo "【常用命令】"
    echo "  查看状态:        fail2ban-client status"
    echo "  实时监控:        fail2ban-monitor"
    echo "  查看统计:        fail2ban-stats"
    echo "  解封 IP:         fail2ban-unban <IP>"
    echo "  解封所有:        fail2ban-unban all"
    echo "  查看日志:        tail -f /var/log/fail2ban.log"
    echo ""
    echo "【配置文件位置】"
    echo "  主配置:          /etc/fail2ban/jail.d/proxy.conf"
    echo "  Sing-box 过滤器: /etc/fail2ban/filter.d/sing-box.conf"
    echo "  Snell 过滤器:    /etc/fail2ban/filter.d/snell.conf"
    echo ""
    echo "【当前配置】"
    echo "  封禁时长:        $BANTIME 秒 ($(($BANTIME/3600)) 小时)"
    echo "  时间窗口:        $FINDTIME 秒 ($(($FINDTIME/60)) 分钟)"
    echo "  失败阈值:        $MAXRETRY 次"
    echo ""
    echo "【卸载】"
    echo "  运行命令:        uninstall-fail2ban"
    echo ""
    echo "======================================"
}

# 主函数
main() {
    clear
    echo "======================================"
    echo "  Fail2ban 自动安装配置脚本"
    echo "  版本: 1.0"
    echo "======================================"
    echo ""
    
    check_root
    detect_os
    
    # 检查是否已安装
    if command -v fail2ban-client > /dev/null 2>&1; then
        log_warn "检测到 Fail2ban 已安装"
        read -p "是否重新配置？(y/n): " RECONFIG
        if [ "$RECONFIG" != "y" ] && [ "$RECONFIG" != "Y" ]; then
            log_info "退出安装"
            exit 0
        fi
    else
        install_fail2ban
    fi
    
    check_services
    
    if [ "$SING_BOX_EXISTS" = true ]; then
        create_singbox_filter
    fi
    
    if [ "$SNELL_EXISTS" = true ]; then
        create_snell_filter
    fi
    
    create_jail_config
    test_filters
    verify_config
    start_service
    show_status
    create_management_scripts
    create_uninstall_script
    show_usage
    
    log_info "安装完成！建议运行 'fail2ban-monitor' 查看实时状态"
}

# 执行主函数
main

